### ISSUE TITLE
still have duplicate packages after run yarn-deduplicate

### ISSUE THREAD

**Issue by findfish** [atlassian/yarn-deduplicate#112]
![image](https://user-images.githubusercontent.com/19707133/99258802-0fa88b80-2854-11eb-98ed-8e5263161931.png)

![image](https://user-images.githubusercontent.com/19707133/99259054-6d3cd800-2854-11eb-892d-f9aa37769c2c.png)

**Comment by scinos** [comment]
That's expected. From the docs

> It is important to note that we do not consider duplicated packages when the version ranges don't overlap. For example, if your project depends on underscore@^1.0.0 and underscore@^2.0.0. Your project will end up with two versions of underscore, and yarn-deduplicate won't change that.

`bl@^1.0.0` and `bl@^4.0.3` do not overlap and thus they can't be deduplicated automatically.
