### ISSUE TITLE
invalid package.json files in .history breaks flow type checker

### ISSUE THREAD

**Issue by bj00rn** [atlassian/yarn-deduplicate#14]
flow type checks json files under node_modules by default

The following json files are invalid causing flow to fail:

- node_modules/yarn/deduplicate/.history/package_20181018055733.json:
- node_modules/yarn-deduplicate/.history/package_20181018055741.json

Can we remove/fix these files?

Steps to reproduce:
````
$ yarn flow check

Error -----------------------------------------node_modules/yarn/deduplicate/.history/package_20181018055733.json:41:3

Unexpected token }

   41|   }
         ^


Error ------------------------------------------ node_modules/yarn-deduplicate/.history/package_20181018055741.json:41:3

Unexpected token }

   41|   }
         ^
```

**Comment by scinos** [comment]
🤦‍♂️ 
Sorry, I screw up the packaging. `.history` should never be part of the package.
