### ISSUE TITLE
Motivation

### ISSUE THREAD

**Issue by saulshanabrook** [atlassian/yarn-deduplicate#18]
Is there a relevant yarn issue that this package is resolving? If so, could it be added to the README? This seems like behavior that should be in yarn by default.

**Comment by rcchen** [comment]
It should definitely be in `yarn` but there appear to be disagreements about intended behavior (see https://github.com/yarnpkg/yarn/issues/3967 for another related issue)

**Comment by saulshanabrook** [comment]
Thank you! I think then I can close this.
