### ISSUE TITLE
Update to yarn-tools versus a new package

### ISSUE THREAD

**Issue by rcchen** [atlassian/yarn-deduplicate#19]
Hi there, big fan of `yarn-tools`, and I suppose its successor, `yarn-deduplicate`

Out of curiosity, why was this not released as a new major version of `yarn-tools` to reflect the API breaks? Is it simply because of a reduction in planned scope of the original `yarn-tools`?

Thanks!

**Comment by scinos** [comment]
Hi @rcchen 

It was mostly about the scope reduction. When I started `yarn-tools` I had more tools in mind, but those eventually got into yarn itself (like auto-resolving merge conflicts). And then I figured out that if I ever release more "tools", they will probably be better as their own package anyway. So I renamed it to `yarn-dedupe`, but that package was taken. Thus `yarn-deduplicate` was born.
