### ISSUE TITLE
Where does mostCommon come from?

### ISSUE THREAD

**Issue by leipert** [atlassian/yarn-deduplicate#22]
Where does mostCommon come from?

Looking at the source https://github.com/atlassian/yarn-deduplicate/blob/6462b2bee267bc35b92e318de15afdf5cdb598c6/cli.js#L26, the `mostCommon` option from commander is probably always undefined. I assume that this is supposed to be the strategy?

**Comment by scinos** [comment]
Fixed and released in 1.0.4
