### ISSUE TITLE
Enable CircleCI for PRs

### ISSUE THREAD

**Issue by chinesedfan** [atlassian/yarn-deduplicate#41]
> By default, CircleCI does not build PRs from forked repositories. To change this setting, go to the Advanced Settings of your project and set the Build forked pull requests option to On.

See [CircleCI docs](https://circleci.com/docs/2.0/oss/#build-pull-requests-from-forked-repositories). And maybe you will also like **Only build pull requests**.

**Comment by scinos** [comment]
Not relevant anymore, moved to GitHub actions
