### ISSUE TITLE
Didn't deduplicate

### ISSUE THREAD

**Issue by xstable** [atlassian/yarn-deduplicate#42]
I got this dedublicate warnings in my Project: 

> warning "npm#JSONStream@^1.3.5" could be deduped from "1.3.5" to "JSONStream@1.3.5"
> warning "npm#abbrev@~1.1.1" could be deduped from "1.1.1" to "abbrev@1.1.1"
> warning "npm#ansicolors@~0.3.2" could be deduped from "0.3.2" to "ansicolors@0.3.2"
> warning "npm#ansistyles@~0.1.3" could be deduped from "0.1.3" to "ansistyles@0.1.3"
> warning "npm#aproba@^2.0.0" could be deduped from "2.0.0" to "aproba@2.0.0"
> warning "npm#archy@~1.0.0" could be deduped from "1.0.0" to "archy@1.0.0"
> warning "npm#bin-links@^1.1.2" could be deduped from "1.1.2" to "bin-links@1.1.2"
> warning "npm#bluebird@^3.5.3" could be deduped from "3.5.3" to "bluebird@3.5.3"
> warning "npm#byte-size@^5.0.1" could be deduped from "5.0.1" to "byte-size@5.0.1"
> warning "npm#cacache@^11.3.2" could be deduped from "11.3.2" to "cacache@11.3.2"
> warning "npm#call-limit@~1.1.0" could be deduped from "1.1.0" to "call-limit@1.1.0"
> warning "npm#chownr@^1.1.1" could be deduped from "1.1.1" to "chownr@1.1.1"
> warning "npm#ci-info@^2.0.0" could be deduped from "2.0.0" to "ci-info@2.0.0"
> warning "npm#cli-columns@^3.1.2" could be deduped from "3.1.2" to "cli-columns@3.1.2"
> warning "npm#cli-table3@^0.5.1" could be deduped from "0.5.1" to "cli-table3@0.5.1"
> warning "npm#cmd-shim@~2.0.2" could be deduped from "2.0.2" to "cmd-shim@2.0.2"
> warning "npm#columnify@~1.5.4" could be deduped from "1.5.4" to "columnify@1.5.4"
> warning "npm#config-chain@^1.1.12" could be deduped from "1.1.12" to "config-chain@1.1.12"
> warning "npm#detect-indent@~5.0.0" could be deduped from "5.0.0" to "detect-indent@5.0.0"
> warning "npm#detect-newline@^2.1.0" could be deduped from "2.1.0" to "detect-newline@2.1.0"
> warning "npm#dezalgo@~1.0.3" could be deduped from "1.0.3" to "dezalgo@1.0.3"
> warning "npm#editor@~1.0.0" could be deduped from "1.0.0" to "editor@1.0.0"
> warning "npm#figgy-pudding@^3.5.1" could be deduped from "3.5.1" to "figgy-pudding@3.5.1"
> warning "npm#find-npm-prefix@^1.0.2" could be deduped from "1.0.2" to "find-npm-prefix@1.0.2"
> warning "npm#fs-vacuum@~1.2.10" could be deduped from "1.2.10" to "fs-vacuum@1.2.10"
> warning "npm#fs-write-stream-atomic@~1.0.10" could be deduped from "1.0.10" to "fs-write-stream-atomic@1.0.10"
> warning "npm#gentle-fs@^2.0.1" could be deduped from "2.0.1" to "gentle-fs@2.0.1"
> warning "npm#glob@^7.1.3" could be deduped from "7.1.3" to "glob@7.1.3"
> warning "npm#graceful-fs@^4.1.15" could be deduped from "4.1.15" to "graceful-fs@4.1.15"
> warning "npm#has-unicode@~2.0.1" could be deduped from "2.0.1" to "has-unicode@2.0.1"
> warning "npm#hosted-git-info@^2.7.1" could be deduped from "2.7.1" to "hosted-git-info@2.7.1"
> warning "npm#inflight@~1.0.6" could be deduped from "1.0.6" to "inflight@1.0.6"
> warning "npm#inherits@~2.0.3" could be deduped from "2.0.3" to "inherits@2.0.3"
> warning "npm#ini@^1.3.5" could be deduped from "1.3.5" to "ini@1.3.5"
> warning "npm#init-package-json@^1.10.3" could be deduped from "1.10.3" to "init-package-json@1.10.3"
> warning "npm#is-cidr@^3.0.0" could be deduped from "3.0.0" to "is-cidr@3.0.0"
> warning "npm#json-parse-better-errors@^1.0.2" could be deduped from "1.0.2" to "json-parse-better-errors@1.0.2"
> warning "npm#lazy-property@~1.0.0" could be deduped from "1.0.0" to "lazy-property@1.0.0"
> warning "npm#libcipm@^3.0.3" could be deduped from "3.0.3" to "libcipm@3.0.3"
> warning "npm#libnpm@^2.0.1" could be deduped from "2.0.1" to "libnpm@2.0.1"
> warning "npm#libnpmhook@^5.0.2" could be deduped from "5.0.2" to "libnpmhook@5.0.2"
> warning "npm#libnpx@^10.2.0" could be deduped from "10.2.0" to "libnpx@10.2.0"
> warning "npm#lock-verify@^2.0.2" could be deduped from "2.1.0" to "lock-verify@2.1.0"
> warning "npm#lockfile@^1.0.4" could be deduped from "1.0.4" to "lockfile@1.0.4"
> warning "npm#lodash._baseuniq@~4.6.0" could be deduped from "4.6.0" to "lodash._baseuniq@4.6.0"
> warning "npm#lodash.clonedeep@~4.5.0" could be deduped from "4.5.0" to "lodash.clonedeep@4.5.0"
> warning "npm#lodash.union@~4.6.0" could be deduped from "4.6.0" to "lodash.union@4.6.0"
> warning "npm#lodash.uniq@~4.5.0" could be deduped from "4.5.0" to "lodash.uniq@4.5.0"
> warning "npm#lodash.without@~4.4.0" could be deduped from "4.4.0" to "lodash.without@4.4.0"
> warning "npm#lru-cache@^4.1.5" could be deduped from "4.1.5" to "lru-cache@4.1.5"
> warning "npm#meant@~1.0.1" could be deduped from "1.0.1" to "meant@1.0.1"
> warning "npm#mississippi@^3.0.0" could be deduped from "3.0.0" to "mississippi@3.0.0"
> warning "npm#mkdirp@~0.5.1" could be deduped from "0.5.1" to "mkdirp@0.5.1"
> warning "npm#move-concurrently@^1.0.1" could be deduped from "1.0.1" to "move-concurrently@1.0.1"
> warning "npm#node-gyp@^3.8.0" could be deduped from "3.8.0" to "node-gyp@3.8.0"
> warning "npm#nopt@~4.0.1" could be deduped from "4.0.1" to "nopt@4.0.1"
> warning "npm#normalize-package-data@^2.5.0" could be deduped from "2.5.0" to "normalize-package-data@2.5.0"
> warning "npm#npm-audit-report@^1.3.2" could be deduped from "1.3.2" to "npm-audit-report@1.3.2"
> warning "npm#npm-cache-filename@~1.0.2" could be deduped from "1.0.2" to "npm-cache-filename@1.0.2"
> warning "npm#npm-install-checks@~3.0.0" could be deduped from "3.0.0" to "npm-install-checks@3.0.0"
> warning "npm#npm-lifecycle@^2.1.0" could be deduped from "2.1.0" to "npm-lifecycle@2.1.0"
> warning "npm#npm-package-arg@^6.1.0" could be deduped from "6.1.0" to "npm-package-arg@6.1.0"
> warning "npm#npm-packlist@^1.3.0" could be deduped from "1.4.1" to "npm-packlist@1.4.1"
> warning "npm#npm-pick-manifest@^2.2.3" could be deduped from "2.2.3" to "npm-pick-manifest@2.2.3"
> warning "npm#npm-registry-fetch@^3.9.0" could be deduped from "3.9.0" to "npm-registry-fetch@3.9.0"
> warning "npm#npm-user-validate@~1.0.0" could be deduped from "1.0.0" to "npm-user-validate@1.0.0"
> warning "npm#npmlog@~4.1.2" could be deduped from "4.1.2" to "npmlog@4.1.2"
> warning "npm#once@~1.4.0" could be deduped from "1.4.0" to "once@1.4.0"
> warning "npm#opener@^1.5.1" could be deduped from "1.5.1" to "opener@1.5.1"
> warning "npm#osenv@^0.1.5" could be deduped from "0.1.5" to "osenv@0.1.5"
> warning "npm#pacote@^9.4.1" could be deduped from "9.5.0" to "pacote@9.5.0"
> warning "npm#path-is-inside@~1.0.2" could be deduped from "1.0.2" to "path-is-inside@1.0.2"
> warning "npm#promise-inflight@~1.0.1" could be deduped from "1.0.1" to "promise-inflight@1.0.1"
> warning "npm#qrcode-terminal@^0.12.0" could be deduped from "0.12.0" to "qrcode-terminal@0.12.0"
> warning "npm#query-string@^6.2.0" could be deduped from "6.2.0" to "query-string@6.2.0"
> warning "npm#qw@~1.0.1" could be deduped from "1.0.1" to "qw@1.0.1"
> warning "npm#read@~1.0.7" could be deduped from "1.0.7" to "read@1.0.7"
> warning "npm#read-cmd-shim@~1.0.1" could be deduped from "1.0.1" to "read-cmd-shim@1.0.1"
> warning "npm#read-installed@~4.0.3" could be deduped from "4.0.3" to "read-installed@4.0.3"
> warning "npm#read-package-json@^2.0.13" could be deduped from "2.0.13" to "read-package-json@2.0.13"
> warning "npm#read-package-tree@^5.2.2" could be deduped from "5.2.2" to "read-package-tree@5.2.2"
> warning "npm#request@^2.88.0" could be deduped from "2.88.0" to "request@2.88.0"
> warning "npm#retry@^0.12.0" could be deduped from "0.12.0" to "retry@0.12.0"
> warning "npm#rimraf@^2.6.3" could be deduped from "2.6.3" to "rimraf@2.6.3"
> warning "npm#safe-buffer@^5.1.2" could be deduped from "5.1.2" to "safe-buffer@5.1.2"
> warning "npm#semver@^5.6.0" could be deduped from "5.6.0" to "semver@5.6.0"
> warning "npm#sha@~2.0.1" could be deduped from "2.0.1" to "sha@2.0.1"
> warning "npm#slide@~1.1.6" could be deduped from "1.1.6" to "slide@1.1.6"
> warning "npm#sorted-object@~2.0.1" could be deduped from "2.0.1" to "sorted-object@2.0.1"
> warning "npm#sorted-union-stream@~2.1.3" could be deduped from "2.1.3" to "sorted-union-stream@2.1.3"
> warning "npm#ssri@^6.0.1" could be deduped from "6.0.1" to "ssri@6.0.1"
> warning "npm#stringify-package@^1.0.0" could be deduped from "1.0.0" to "stringify-package@1.0.0"
> warning "npm#tar@^4.4.8" could be deduped from "4.4.8" to "tar@4.4.8"
> warning "npm#text-table@~0.2.0" could be deduped from "0.2.0" to "text-table@0.2.0"
> warning "npm#tiny-relative-date@^1.3.0" could be deduped from "1.3.0" to "tiny-relative-date@1.3.0"
> warning "npm#uid-number@0.0.6" could be deduped from "0.0.6" to "uid-number@0.0.6"
> warning "npm#umask@~1.1.0" could be deduped from "1.1.0" to "umask@1.1.0"
> warning "npm#unique-filename@^1.1.1" could be deduped from "1.1.1" to "unique-filename@1.1.1"
> warning "npm#unpipe@~1.0.0" could be deduped from "1.0.0" to "unpipe@1.0.0"
> warning "npm#update-notifier@^2.5.0" could be deduped from "2.5.0" to "update-notifier@2.5.0"
> warning "npm#uuid@^3.3.2" could be deduped from "3.3.2" to "uuid@3.3.2"
> warning "npm#validate-npm-package-license@^3.0.4" could be deduped from "3.0.4" to "validate-npm-package-license@3.0.4"
> warning "npm#validate-npm-package-name@~3.0.0" could be deduped from "3.0.0" to "validate-npm-package-name@3.0.0"
> warning "npm#which@^1.3.1" could be deduped from "1.3.1" to "which@1.3.1"
> warning "npm#worker-farm@^1.6.0" could be deduped from "1.6.0" to "worker-farm@1.6.0"
> warning "npm#write-file-atomic@^2.4.2" could be deduped from "2.4.2" to "write-file-atomic@2.4.2"
> warning "npm#readable-stream#inherits@^2.0.3" could be deduped from "2.0.3" to "inherits@2.0.3"
> warning "npm#readable-stream#string_decoder@^1.1.1" could be deduped from "1.2.0" to "string_decoder@1.2.0"
> warning "npm#readable-stream#util-deprecate@^1.0.1" could be deduped from "1.0.2" to "util-deprecate@1.0.2"
> 

running `yarn-deduplicate yarn.lock` has no effect. 

This is my package.json:
```

{
  "dependencies": {
    "@babel/runtime": "^7.3.4",
    "fbjs": "^0.8.17",
    "lodash": "^4.17.11",
    "lodash.isequal": "^4.5.0",
    "metro-react-native-babel-preset": "^0.52.0",
    "native-base": "^2.12.0",
    "npm": "^6.8.0",
    "prop-types": "^15.6.1",
    "react": "16.6.3",
    "react-devtools": "^3.2.1",
    "react-native": "0.58.5",
    "react-native-cacheable-image": "^2.0.0",
    "react-native-fast-image": "^5.1.2",
    "react-native-firebase": "^4.3.8",
    "react-native-grid-list": "^1.0.9",
    "react-native-image-zoom-viewer": "^2.2.23",
    "react-native-modal-dropdown": "^0.6.2",
    "react-native-render-html": "^3.9.3",
    "react-native-safe-area-view": "^0.7.0",
    "react-native-scrolling-menu": "experiment322/react-native-scrolling-menu",
    "react-native-transformable-image": "https://github.com/xstable/react-native-transformable-image.git",
    "react-native-vector-icons": "^6.1.0",
    "react-native-video": "tranvinhtruong/react-native-video",
    "react-native-video-player": "https://github.com/tranvinhtruong/react-native-video-player",
    "react-native-youtube": "^1.1.0",
    "react-navigation": "^1.5.11",
    "reactotron-react-native": "^1.14.0",
    "webpack": "^4.5.0"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/preset-flow": "^7.0.0",
    "@babel/register": "^7.0.0",
    "babel-core": "^7.0.0-bridge.0",
    "babel-eslint": "^9.0.0",
    "babel-jest": "^23.4.2",
    "babel-plugin-transform-remove-console": "^6.9.2",
    "eslint": "^5.12.1",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^6.1.1",
    "eslint-plugin-react": "^7.11.1",
    "eslint-plugin-react-native": "^3.2.1",
    "jest": "23.6.0",
    "react-test-renderer": "16.6.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

Any idea, why deduplication didn't work?

**Comment by chinesedfan** [comment]
After `yarn-deduplicate`, please run `yarn` again. Or `yarn check` may print above warnings.

**Comment by suther** [comment]
I've figured out. that I don't need this package for the App. So I only removed it.
Ticket can be closed.
