### ISSUE TITLE
Document why this is necessary

### ISSUE THREAD

**Issue by maschwenk** [atlassian/yarn-deduplicate#56]
This thing works, but reading the Yarn documentation seems to suggest it shouldn't be necessary. I've tracked a few issues in the Yarn repo that suggest potential root causes, but I'm sure the authors of this package would be in a better position to explain it 😄

**Comment by scinos** [comment]
Explained in https://github.com/atlassian/yarn-deduplicate/blob/master/README.md#why-is-this-necessary

**Comment by 7rulnik** [comment]
Also see  https://github.com/yarnpkg/berry/pull/1558#issuecomment-655514065
