### ISSUE TITLE
Support yarn berry

### ISSUE THREAD

**Issue by christophehurpeau** [atlassian/yarn-deduplicate#64]
Hello,

It seems yarn 2 still needs this. I started working on a version that only supports yarn berry: https://github.com/christophehurpeau/yarn-deduplicate/tree/wip-berry

My findings are:
- use of @yarnpkg/parsers instead of @yarnpkg/lockfile. It also means that the packages are not split automaticly like it was the case in @yarnpkg/lockfile, so merging has to be handled manually
- there is a new information before the version (I called it source, but not sure if it's the right name). In my lockfiles, it's almost awlays npm, except for different versions of resolve, like `resolve@^1.10.0` and other patched versions of resolve, like `resolve@patch:resolve@^1.10.0#builtin<compat/resolve>`

Do you plan to work on a berry version ?

**Comment by Bnaya** [comment]
yarn berry is under very active development,
I believe it will be possible to bake that into it

**Comment by SimenB** [comment]
@scinos @rjatkins any thoughts on this? For v2/berry it could be designed as a plugin rather than a separate tool, so we could run `yarn deduplicate` instead of `yarn-deduplicate`. I.e. the approach of (the unmaintained?) https://github.com/eps1lon/yarn-plugin-deduplicate

**Comment by scinos** [comment]
It makes a lot of sense to use the new plugin framework.

I'll try to look into writing a plugin (or reviving https://github.com/eps1lon/yarn-plugin-deduplicate) soon, first I need to understand how the plugin system works and get my hands on a few yarn v2 repos with duplicated packages to test everything.

If anyone wants to start working on it meanwhile, it would be great :)

**Comment by scinos** [comment]
There is also this https://github.com/yarnpkg/berry/pull/1558

**Comment by JounQin** [comment]
https://github.com/yarnplugins/yarn-plugin-deduplicate/issues/13

I hope we can reconsider this.

I'll raise a PR for it like https://github.com/ds300/patch-package/pull/507.

**Comment by christophehurpeau** [comment]
@JounQin note that I have working fork here https://github.com/christophehurpeau/yarn-deduplicate / https://www.npmjs.com/package/yarn-berry-deduplicate
I hope to convert it to a yarn plugin some day if this is still not implemented in yarn

**Comment by JounQin** [comment]
@christophehurpeau Thanks for your information, but I'd like to raise a PR for `yarn-deduplicate` itself to support yarn v1 and v2+ at the same time~

**Comment by scinos** [comment]
Yarn V2+ supports `yarn dedupe` natively. What's the goal of adding support for V2 to this tool?

**Comment by JounQin** [comment]
> Yarn V2+ supports yarn dedupe natively. What's the goal of adding support for V2 to this tool?

It doesn't support `--strategy fewer`, yet.

See also https://github.com/yarnpkg/berry/issues/2297

**Comment by scinos** [comment]
Looks like nobody is opposed to add the `fewer` strategy to Yarn. 

I haven't looked at the `yarn dedupe` code in ages, but, from memory, it was really similar to `yarn-deduplicate`. Meaning that implementing the strategy should be relatively easy. 

I may have some time this week to have a look.

**Comment by JounQin** [comment]
> I may have some time this week to have a look.

Do you mean you want to work this this week? That would be great! I and my colleague were going to working on this feature also but on `yarn-deduplicate`'s side.

The benefit is, we can use `prepare: yarn-duplicate` script to run `yarn-duplicate` every time on installation. But `prepare: yarn dedupe` will run into a dead loop, at least for now.

(For prepare script support for yarn berry, see also https://github.com/un-es/yarn-plugin-prepare-lifecycle)

---

Besides, can we reopen this issue first?
