### ISSUE TITLE
Feature request: --check flag

### ISSUE THREAD

**Issue by singingwolfboy** [atlassian/yarn-deduplicate#67]
It would be nice if `yarn-deduplicate` supported a `--check` flag, which could be used on CI. The expected behavior would be: if called with the `--check` flag, `yarn-deduplicate` does _not_ modify the `yarn.lock` file, but instead checks to see if it _should_ be modified. If so, it exits with a non-zero exit code.

**Comment by Bnaya** [comment]
I just came to open the exact same issue:)

**Comment by Bnaya** [comment]
Going over the code,
seems like theres the fail flag, but it's not documented 
https://github.com/atlassian/yarn-deduplicate/blob/master/__tests__/cli.js#L24-L44

**Comment by scinos** [comment]
Thanks for the report!

As @Bnaya pointed out, it is already supported but not very well documented. I added a section to the README and improved the help description
