### ISSUE TITLE
Updating Packages already de-duped by yarn

### ISSUE THREAD

**Issue by nikmash** [atlassian/yarn-deduplicate#91]
I was wondering if this module can be used to update packages that are already de-duped by yarn. For example say there are multiple modules that have module X defined as `^0.5.0` `^0.5.1` etc. and currently it has already been de-duped by yarn and uses `v0.5.1` would this be able to update it to `v0.5.5` since this is the latest version that satisfies every module's condition?

**Comment by torifat** [comment]
Not sure why you need this tool in that case! Can't you just upgrade it with yarn?

**Comment by scinos** [comment]
Even though I'd love to have a tool to automatically update transitive dependencies (afaik `yarn` doesn't do it "natively"), I think it is beyond the scope of `yarn-deduplicate`, it should be a different package
